//Ejemplo utilizando solamente catch()
const promesaNueva = new Promise( (resolved, rejected) => {
    //Declaramos el ejemplo como si se cumpliera lo que pedimos.
        const expresion = false;
        if(expresion){
            // Definimos la promesa
            resolved( 'Resolvi贸 correctamente' );
    //En caso que ocurri贸 un error y no se resolvi贸 la petici贸n anterior
        } else {
            rejected( 'Se produjo un error' );
        }
    });
    
//Mandamos a llamar a la promesa para ejecutarla  
promesaNueva
    .then( valor => console.log(valor) )
//Si ocurre un error lo podemos manejar con .catch().
    .catch( error => console.log(error) );